name: Automatically Update Dependencies
on:
  pull_request:

jobs:
  auto-update-dependencies:
    name: Auto-Approve and enable Auto-Merge for all Dependabot PRs
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    steps:
    - id: auto-approve-dependabot
      uses: hmarr/auto-approve-action@v2.0.0
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 1
    - id: enable-automerge
      name: Enable Github Automerge
      uses: ./
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
