name: Test
on:
  pull_request:
  schedule:
    # Scheduled build so pipeline failures are noticed quicker.
    - cron: '17 4 * * 2,5'


jobs:
  # Lint & build
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 1
    - uses: actions/setup-node@master
    - name: Install Dependencies
      run: npm ci --ignore-scripts
    - name: Lint
      run: npm run format-check
    - name: Build
      run: npm run build